# Starter pipeline
- task: UiPathPack@3
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'Testing'
    orchestratorConnection: 'Orchestrator Application Connection uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- task: UiPathTest@3
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Orchestrator Application Connection uipath'
    folderName: 'Shared'
    testReportDestination: '$(Build.ArtifactStagingDirectory)\Output'
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
